services:
  - type: web
    name: taxlaw-crawler
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py
    autoDeploy: false
    envVars:
      - key: PYTHONUNBUFFERED
        value: 'TRUE'
